project:
  type: book

bibliography: book.bib

book:
  title: "R Packages (2e)"
  author-meta: "Hadley Wickham and Jenny Bryan"
  description-meta: |
    Learn how to create a package, the fundamental unit of shareable, reusable, 
    and reproducible R code.
  cover-image: images/cover.png

  reader-mode: true
  site-url: https://r-pkgs.org/
  repo-url: https://github.com/hadley/r-pkgs/
  repo-actions: [edit, issue]
  
  chapters:
  - index.Rmd
  - Preface.Rmd
  
  - part: Getting started
    chapters: 
    - Introduction.Rmd
    - Whole-game.Rmd
    - Setup.Rmd
    - Structure.Rmd
    - Workflow101.Rmd
    - Package-within.Rmd
  
  - part: Package components
    chapters:
    - Code.Rmd
    - Data.Rmd
    - misc.Rmd
  
  - part: Package metadata
    chapters:
    - Metadata.Rmd
    - dependencies.Rmd
    - license.Rmd
  
  - part: Testing
    chapters:
    - testing-basics.Rmd
    - testing-design.Rmd
    - testing-advanced.Rmd
    
  - part: Documentation
    chapters:
    - man.Rmd
    - vignettes.Rmd
    - other-markdown.Rmd
    - website.Rmd
  
  - part: Maintenance and distribution
    chapters:
    - check.Rmd
    - continuous-integration.Rmd
    - release.Rmd
    - lifecycle.Rmd

  - references.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    code-link: true
    include-in-header: "plausible.html"

editor: visual
