project:
  type: book
  output-dir: _book

book:
  title: "R Packages (2e)"

  author-meta: "Hadley Wickham, and Jenny Bryan"
  date-meta: today
  description-meta: |
    This book will teach you how to create a package, the fundamental unit of
    shareable, reusable, and reproducible R code.

  reader-mode: true

  page-footer:
    left: |
      R Packages (2e) was written by Hadley Wickham and Jenny Bryan
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  site-url: https://r-pkgs.org/
  repo-url: https://github.com/hadley/r-packages/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.Rmd
    
    - Preface.Rmd
    
    - Introduction.Rmd
    - Whole-game.Rmd
    - Setup.Rmd
    - Structure.Rmd
    - Workflow101.Rmd
    - Package-within.Rmd
    
    - Code.Rmd
    - data.Rmd
    - misc.Rmd
    
    # DESCRIPTION and NAMESPACE
    - Metadata.Rmd
    - dependencies.Rmd
    - license.Rmd
    
    - testing-basics.Rmd
    - testing-design.Rmd
    - testing-advanced.Rmd
    
    - man.Rmd
    - vignettes.Rmd
    - other-markdown.Rmd
    - website.Rmd
    
    - check.Rmd
    - continuous-integration.Rmd
    - release.Rmd
    - lifecycle.Rmd

format:
  html:
    theme:
      - cosmo
      - style.css
    cover-image: cover.png
    code-link: true
    include-in-header: "plausible.html"
    callout-appearance: simple

editor: visual
